name: Build ESP8266 Gateway Firmware

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kbittle/esp8266-build-env:latest

    defaults:
      run:
        working-directory: esp-gateway-project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Firmware
        shell: bash
        run: |
          make -j$(nproc) CONFIG_SDK_PYTHON=python3

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp8266-firmware-binaries
          path: |
            esp-gateway-project/build/*.bin
            esp-gateway-project/build/bootloader/bootloader.bin
            esp-gateway-project/build/partition_table/partition-table.bin
